#!/bin/bash
set -eou pipefail

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
SCRIPT_NAME="$(basename "$(realpath "$0")")"
source "$(realpath "$SCRIPT_DIR/../git-shell-env/lib/bash/gitsrv.lib.bash")"

SCRIPT_USAGE="${SCRIPT_NAME} FROM TO_DIR"

FROM="${1:-}"
TO_DIR="${2:-}"

[ -n "$FROM" ] || usage err
[ -n "$TO_DIR" ] || usage err

SRV="/srv/git"

[ ! -e "$SRV/$TO_DIR" ] || err "repository exists: $TO_DIR"

umask 007
git clone --mirror "$FROM" "$SRV/$TO_DIR"
chown -R git:gitusr /srv/git
chmod -R o-rwx /srv/git
chmod -R ug+rw /srv/git

exit 0
